version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-name: "@angular/cli"
      - dependency-name: "@fullcalendar/core"
    open-pull-requests-limit: 3
